# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ulbie
email: ulbieee@gmail.com
description: > 
  Day, drawing, graphic, identity, system, programing, interaction.
baseurl: "" # the subpath of your site, e.g. /blog
url: "ulbie.github.io/blog" # the base hostname & protocol for your site
twitter_username: past_ulbie
github_username:  ulbie

# Build settings
markdown: kramdown

